### ISSUE TITLE
use pushd and popd to switch directory

### ISSUE THREAD

**Issue by m943040028** [OpenTrustGroup/update_otg_master_branch#1]
https://github.com/OpenTrustGroup/update_otg_master_branch/blob/94ab877548637fdff9ddcaf099f925498fa0a569/update_otg_master.sh#L14

You might able to use pushd and popd
https://en.wikipedia.org/wiki/Pushd_and_popd

**Comment by kong1191** [comment]
Implemented in 9e6713b56b85319a6e6c074a58160f3b3fe3cc1f
